[project]
name = "codementor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.3",
    "bcrypt==4.3.0",
    "celery>=5.6.2",
    "chonkie>=1.5.5",
    "docling>=2.73.0",
    "fastapi>=0.128.1",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "notebook>=7.5.3",
    "ollama>=0.6.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.12.0",
    "pydantic[email]>=2.12.5",
    "pymupdf>=1.27.1",
    "pymupdf-layout>=1.27.1",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "qdrant-client>=1.16.2",
    "redis>=7.2.0",
    "sentence-transformers>=5.2.2",
    "sqlalchemy>=2.0.46",
    "tqdm>=4.67.3",
    "uvicorn[standard]>=0.40.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]
