line-length = 100
target-version = "py312"

[lint]
select = ["E", "F", "I", "W"]
ignore = ["E501"]  # line too long — handled by formatter

[lint.per-file-ignores]
"alembic/*" = ["E", "F", "I", "W"]  # ignore migration files

[format]
quote-style = "double"
indent-style = "space"
exclude = ["alembic/*"]