"""add topic field to rag_documents

Revision ID: 2568068a2b68
Revises: 3d95fa5a803b
Create Date: 2026-02-20 23:08:32.892992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2568068a2b68'
down_revision: Union[str, Sequence[str], None] = '3d95fa5a803b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('topic', sa.String(length=50), nullable=False))
    op.alter_column('rag_documents', 'chunks_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rag_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rag_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_rag_documents_language'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_user_id'), table_name='rag_documents')
    op.create_index(op.f('ix_rag_documents_topic'), 'rag_documents', ['topic'], unique=False)
    op.drop_column('rag_documents', 'language')
    op.drop_column('rag_documents', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rag_documents', sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rag_documents_topic'), table_name='rag_documents')
    op.create_index(op.f('ix_rag_documents_user_id'), 'rag_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_language'), 'rag_documents', ['language'], unique=False)
    op.alter_column('rag_documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('rag_documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rag_documents', 'chunks_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rag_documents', 'topic')
    # ### end Alembic commands ###
