"""add rag_documents table

Revision ID: 3d95fa5a803b
Revises: 6f9bff6ddd24
Create Date: 2026-02-15 22:31:57.070530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d95fa5a803b'
down_revision: Union[str, Sequence[str], None] = '6f9bff6ddd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_id'), 'rag_documents', ['id'], unique=False)
    op.create_index(op.f('ix_rag_documents_is_public'), 'rag_documents', ['is_public'], unique=False)
    op.create_index(op.f('ix_rag_documents_language'), 'rag_documents', ['language'], unique=False)
    op.create_index(op.f('ix_rag_documents_status'), 'rag_documents', ['status'], unique=False)
    op.create_index(op.f('ix_rag_documents_title'), 'rag_documents', ['title'], unique=False)
    op.create_index(op.f('ix_rag_documents_user_id'), 'rag_documents', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_rag_documents_user_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_title'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_status'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_language'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_is_public'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
