"""add sources and rag_used to messages

Revision ID: 680ace4f86cd
Revises: 07325e39ecde
Create Date: 2026-03-04 04:12:25.493369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680ace4f86cd'
down_revision: Union[str, Sequence[str], None] = '07325e39ecde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sources', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('rag_used', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'rag_used')
    op.drop_column('messages', 'sources')
    # ### end Alembic commands ###
