"""add task_id to rag_documents

Revision ID: f888132d8d72
Revises: 680ace4f86cd
Create Date: 2026-04-13 15:48:07.192486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f888132d8d72'
down_revision: Union[str, Sequence[str], None] = '680ace4f86cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('rag_documents', 'task_id')
    # ### end Alembic commands ###
